package com.sktelecom.t1.Models;

import org.springframework.web.multipart.MultipartFile;

public class Players {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players.PlayerID
     *
     * @mbg.generated
     */
    private String playerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players.Position
     *
     * @mbg.generated
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players.pic
     *
     * @mbg.generated
     */
    private String pic;


    private MultipartFile picFile;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players.ID
     *
     * @return the value of players.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players.ID
     *
     * @param id the value for players.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players.PlayerID
     *
     * @return the value of players.PlayerID
     *
     * @mbg.generated
     */
    public String getPlayerid() {
        return playerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players.PlayerID
     *
     * @param playerid the value for players.PlayerID
     *
     * @mbg.generated
     */
    public void setPlayerid(String playerid) {
        this.playerid = playerid == null ? null : playerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players.Position
     *
     * @return the value of players.Position
     *
     * @mbg.generated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players.Position
     *
     * @param position the value for players.Position
     *
     * @mbg.generated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players.age
     *
     * @return the value of players.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players.age
     *
     * @param age the value for players.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players.pic
     *
     * @return the value of players.pic
     *
     * @mbg.generated
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players.pic
     *
     * @param pic the value for players.pic
     *
     * @mbg.generated
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    public MultipartFile getPicFile() {
        return picFile;
    }

    public void setPicFile(MultipartFile picFile) {
        this.picFile = picFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players
     *
     * @mbg.generated
     */


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", playerid=").append(playerid);
        sb.append(", position=").append(position);
        sb.append(", age=").append(age);
        sb.append(", pic=").append(pic);
        sb.append("]");
        return sb.toString();
    }
}